### ISSUE TITLE
FaceForensics++ dataset has masks in image format rather than .avi

### ISSUE THREAD

**Issue by nviable** [nii-yamagishilab/ClassNSeg#1]
Your code seems to expect masks in avi format
`vidcap_mask = cv2.VideoCapture(os.path.join(f_vid_mask, f))`

However the updated FaceForensics++ dataset download code assumes that masks and models are only available in raw image sequence format.

> Masks and models are only available for raw images.

I'll be writing up a workaround for this to just use image streams for the masks which will probably be useful for people trying to replicate or extend your work.

**Comment by honghuy127** [comment]
Yes, create_dataset_Face2Face.py is just for the old FaceForensics dataset.
You can slightly modify create_dataset_Deepfakes.py or create_dataset_FaceSwap.py for the Face2Face part of the FaceForensics++ dataset.
